In [ ]:
import sqlalchemy
import pandas as pd
import yfinance as yf

This code imports the required libraries

In [ ]:
tickersSensex = ['^BSESN']  # Replace with the desired ticker symbol for Sensex index
tickersDOW = ['^DJI']  # Replace with the desired ticker symbol for Dow Jones Industrial Average

The code assigns the ticker symbols for the Sensex index and Dow Jones Industrial Average to the variables tickersSensex and tickersDOW, respectively. These ticker symbols are used to identify specific financial assets on various financial data platforms or APIs.

The Sensex index is the benchmark stock market index of the Bombay Stock Exchange (BSE) in India. The ticker symbol 'BSESN' represents the Sensex index on Yahoo Finance.

The Dow Jones Industrial Average (DJIA) is a widely followed stock market index that represents the performance of 30 large, publicly traded companies in the United States. The ticker symbol 'DJI' represents the Dow Jones Industrial Average on Yahoo Finance.

In the provided code, you are instructed to replace these default ticker symbols ('^BSESN' for Sensex and '^DJI' for Dow Jones) with the desired ticker symbols based on your specific requirements. By replacing the ticker symbols, you can fetch financial data for different indices or stocks using those updated symbols.

In [ ]:
def getdata(tickers):
	data = []
	for ticker in tickers: 
        data.append(yf.download(ticker).reset_index())
    return data

The code defines a function called getdata that takes a list of stock tickers as input. 

Here's a breakdown of what the function does:
* data = []: Initializes an empty list called data to store the retrieved data.
* for ticker in tickers:: This sets up a loop that iterates over each ticker in the tickers list.
* Indentation Issue: Please note that there is an indentation issue in the code you provided. Python relies on proper indentation to define the scope of blocks of code. The following line (data.append(yf.download(ticker).reset_index())) should be indented with four spaces or a tab to be inside the for loop correctly.
* data.append(yf.download(ticker).reset_index()): Within the loop, this line uses the yf.download() function from the yfinance library to download the historical stock data for the current ticker. The reset_index() function is called on the downloaded data to reset the index column and make it a regular column.
* data: After each iteration of the loop, the retrieved data for the current ticker is appended to the data list.

It's worth mentioning that this code assumes that the yf.download() function from the yfinance library is correctly set up and will return the desired stock data for each ticker. The resulting data list will contain the downloaded data for each ticker in the input list.

In [ ]:
india, US  = getdata(tickersSensex), getdata(tickersDOW)

The code  assumes the existence of two lists, tickersSensex and tickersDOW, which contain stock ticker symbols for the BSE SENSEX index in India and the Dow Jones Industrial Average index in the US, respectively. The code then calls the getdata() function to retrieve the data for these ticker symbols and assigns the returned values to variables india and US. Here's a breakdown of what this code does:

* india, US = getdata(tickersSensex), getdata(tickersDOW): This line calls the getdata() function twice, passing tickersSensex and tickersDOW as arguments, respectively. The function is assumed to return data for the provided ticker symbols.

* getdata(tickersSensex): This function call retrieves the historical stock data for the ticker symbols in tickersSensex (associated with the BSE SENSEX index in India). The returned data is assigned to the variable india.

* getdata(tickersDOW): This function call retrieves the historical stock data for the ticker symbols in tickersDOW (associated with the Dow Jones Industrial Average index in the US). The returned data is assigned to the variable US.

The resulting india and US variables will contain the downloaded stock data for the corresponding indices in India and the US, respectively.

In [ ]:
india

In [ ]:
india[0]

In [ ]:
def createengine(name):
    engine = sqlalchemy.create_engine(‘sqlite:///’+name)
    return engine

The code  defines a function called createengine that takes a parameter name, which represents the name of a SQLite database file. Here's a breakdown of what the function does:

* engine = sqlalchemy.create_engine('sqlite:///' + name): This line creates a database engine using SQLAlchemy's create_engine function. The engine is configured to connect to a SQLite database file specified by the name parameter. The 'sqlite:///' + name string is the connection URL for SQLite databases, where name represents the path and name of the SQLite database file.

* return engine: This line returns the created database engine as the output of the function.

In summary, this function creates and returns a SQLAlchemy engine object that is configured to connect to a SQLite database file specified by the name parameter.

In [ ]:
indiaengine = createengine('India.db')  # Provide the desired name for the India database
USengine = createengine('USA.db')  # Provide the desired name for the USA database

The code snippet provided creates SQLite database engines for India and USA, assigning them to the variables indiaengine and USengine, respectively. The createengine() function is called with the desired database names as arguments.

The createengine() function takes a database name as input and uses it to create an engine object using the SQLAlchemy library. The engine object represents the connection to the SQLite database and provides methods for interacting with the database.

In the code snippet, the database names provided are 'India.db' and 'USA.db', respectively. These names are examples, and you can replace them with your desired names for the databases that will store the imported data.

By creating separate database engines for India and USA, you can establish connections to their respective databases and perform operations such as reading, writing, and querying data within each database using the SQLAlchemy library.

In [ ]:
def TOSQL(frames, symbols, engine):
	for frame,symbol in zip(frames, symbols):
 	    frame.to_sql(symbol, engine, index=False)
    print(‘Successfully imported data’)

The code defines a function called T0SQL that takes three parameters: frames, symbols, and engine. Here's a breakdown of what the function does:

* for frame, symbol in zip(frames, symbols):: This line sets up a loop that iterates over the frames and symbols lists simultaneously using the zip() function. It assumes that the frames list contains pandas DataFrame objects, and the symbols list contains corresponding symbols or names for each DataFrame.

* Indentation Issue: Please note that there is an indentation issue in the code you provided. The following line (frame.to_sql(symbol, engine, index=False)) should be indented with four spaces or a tab to be inside the for loop correctly.

* frame.to_sql(symbol, engine, index=False): Within the loop, this line uses the to_sql() method of a pandas DataFrame (frame) to write the DataFrame data to a SQL table. The symbol parameter is used as the table name, and the engine parameter represents the database engine to which the data will be written. The index=False argument specifies that the DataFrame's index should not be included as a separate column in the table.

* Indentation Issue: Please note that there is another indentation issue in the code you provided. The print() function call (print('Successfully imported data')) should also be indented with four spaces or a tab to be inside the for loop correctly.

* print('Successfully imported data'): After each iteration of the loop, this line is executed to print the message 'Successfully imported data' to the console. It indicates that the data from the current DataFrame has been successfully written to the corresponding SQL table.


In summary, this function takes a list of DataFrame objects (frames), a list of symbols or table names (symbols), and a database engine (engine) as inputs. It iterates over the DataFrame-symbols pairs, writes each DataFrame's data to a corresponding SQL table using the provided engine, and prints a success message for each iteration.

In [ ]:
TOSQL(india, tickerSensex, indiaengine)

The code you provided calls the T0SQL() function with the arguments india, tickerSensex, and indiaengine. Here's a breakdown of what this code does:

* T0SQL(india, tickerSensex, indiaengine): This function call invokes the T0SQL() function with three arguments:
india: It assumes india is a list of pandas DataFrame objects containing the data to be written to SQL tables.
tickerSensex: It assumes tickerSensex is a list of symbols or table names corresponding to the DataFrame objects in india.
indiaengine: It assumes indiaengine is a SQLAlchemy engine object representing the database engine to which the data will be written.

* for frame, symbol in zip(frames, symbols):: Inside the T0SQL() function, this line sets up a loop that iterates over the india DataFrame objects and the tickerSensex symbols simultaneously using the zip() function.

* frame.to_sql(symbol, engine, index=False): Within the loop, this line uses the to_sql() method of each DataFrame (frame) to write the data to a corresponding SQL table. The symbol parameter is used as the table name, and the engine parameter represents the indiaengine database engine to which the data will be written. The index=False argument specifies that the DataFrame's index should not be included as a separate column in the table.

* print('Successfully imported data'): After each iteration of the loop, this line is executed to print the message 'Successfully imported data' to the console, indicating that the data from the current DataFrame has been successfully written to the corresponding SQL table.

In summary, the T0SQL() function is called with the india DataFrame objects, tickerSensex symbols, and indiaengine database engine as arguments. The function iterates over the DataFrame-symbols pairs, writes each DataFrame's data to a corresponding SQL table using the provided engine, and prints a success message for each iteration.

In summary, the T0SQL() function is called with the india DataFrame objects, tickerDOW symbols, and USengine database engine as arguments. The function iterates over the DataFrame-symbols pairs, writes each DataFrame's data to a corresponding SQL table using the provided engine, and prints a success message for each iteration.

In [ ]:
TOSQL(US, tickerDOW,USengine)


The code T0SQL(US, tickerDOW, USengine) calls the T0SQL() function with the arguments US, tickerDOW, and USengine. Here's a breakdown of what this code does:

* T0SQL(US, tickerDOW, USengine): This function call invokes the T0SQL() function with three arguments:
US: It assumes US is a list of pandas DataFrame objects containing the data to be written to SQL tables.
tickerDOW: It assumes tickerDOW is a list of symbols or table names corresponding to the DataFrame objects in US.
USengine: It assumes USengine is a SQLAlchemy engine object representing the database engine to which the data will be written.

* for frame, symbol in zip(frames, symbols):: Inside the T0SQL() function, this line sets up a loop that iterates over the US DataFrame objects and the tickerDOW symbols simultaneously using the zip() function.

* frame.to_sql(symbol, engine, index=False): Within the loop, this line uses the to_sql() method of each DataFrame (frame) to write the data to a corresponding SQL table. The symbol parameter is used as the table name, and the engine parameter represents the USengine database engine to which the data will be written. The index=False argument specifies that the DataFrame's index should not be included as a separate column in the table.

* print('Successfully imported data'): After each iteration of the loop, this line is executed to print the message 'Successfully imported data' to the console, indicating that the data from the current DataFrame has been successfully written to the corresponding SQL table.